### ISSUE TITLE
Add the possibility to define the amount of USDT that should be invested

### ISSUE THREAD

**Issue by bastians** [antoinebaron-io/moon-doge#1]
Currently, the full balance of the Future wallet is used to buy Doge coins but instead it would be nice if the maximum amount of USDT that should be used can be defined somewhere.

Note: Currently it's also a bit misleading. The total balance is shown, based on that, the amount of coins is that should be bought through a market order is calculated but actually the real amount of USDT that is used is based on the leverage setting of USDTDOGE in your binance account. Maybe this could also be approved and the Future settings (leverage and type cross or isolated) can be also added to the config, then the real amount spend could be calculated. Just an idea.

**Comment by antoinebaron-io** [comment]
you can now set the amount in AMOUNT
