### ISSUE TITLE
Add check how long the last tweet is in the past to avoid order hours later

### ISSUE THREAD

**Issue by bastians** [antoinebaron-io/moon-doge#2]
If the last tweet from Elon Musk is about Doge and the script detects this after the start, currently the script places an order, also when the tweet is hours in the past. This should be improved to avoid orders that are probaly to late and not worth anymore.

**Comment by antoinebaron-io** [comment]
Done !
The tweeter API provide the date and time of the tweet, but not the seconds, so I added as condition that the tweet is not older than one minute
