### ISSUE TITLE
Use Twitter Streaming API to get tweets from Elon in real time

### ISSUE THREAD

**Issue by bastians** [antoinebaron-io/moon-doge#8]
Maybe it would be more efficient to use the Twitter streaming API instead of the user_timeline API to get Tweets from Elon Musk in real-time. With the streaming API, a connection is opened with the settings delivered and tweets can be received in real-time. This would avoid making HTTP requests every second and probably also avoids running out of free HTTP calls.

There are some libraries that could be probably used, like these ones:
* https://github.com/spatie/twitter-streaming-api
* https://github.com/redwebcreation/twitter-stream-api

**Comment by antoinebaron-io** [comment]
Hi,

Yes I will check that, thanks
I put it on my todo list
I am finishing a big project right now and I cant focus on something else

Did you catch the tweets from Yesterday ? I did catch the first, sold at+5%
and Lost 3% on the second tweet : Price was already hight when the bot made
the buy order

**Comment by antoinebaron-io** [comment]
it is done, I close the issue

**Comment by bastians** [comment]
Wow, cool! Thanks! But I saw you actually rewrote the script, therefore I cannot use it for my scenario with Binance. Maybe I can adapt it to the old script in my fork.
